#:schema https://raw.githubusercontent.com/NSPC911/rovr/refs/tags/v0.7.0.dev1/src/rovr/config/schema.json

[interface]
truncate_progress_file_path = true
nerd_font = true
show_line_numbers = true
show_hidden_files = true

[interface.clock]
enabled = false
[interface.compact_mode]
buttons = true

[theme]
transparent = true

[metadata]
filesize_suffix   = "decimal"
filesize_decimals = 2

[keybinds]
new = ["n"]
up = ["up", "i"]
down = ["down", "k"]
up_tree = ["left", "j"]
down_tree = ["right", "l", "enter"]
select_up = ["shift+up", "I"]
select_down = ["shift+down", "K"]
toggle_preview_sidebar = ["O"]
focus_toggle_preview_sidebar = ["o"]
tab_next = ["}"]
tab_previous = ["{"]
tab_new = ["t"]
preview_scroll_left = ["left", "j"]
preview_scroll_right = ["right", "l"]
preview_select_left = ["shift+left", "J"]
preview_select_right = ["shift+right", "L"]

[plugins.zoxide]
enabled = true
show_scores = true

[plugins.bat]
enabled = true
executable = "bat"

[plugins.editor]
enabled = true
file_executable = "powershell -noni -nop -nol -c rovr-helix"
file_suspend = false
open_all_in_editor = true

[plugins.poppler]
threads = 5

[plugins.file_one]
enabled = true
get_description = true

