console_title_template = '@ {{ .Folder }}'
version = 3

[secondary_prompt]
  template = '╰─❯ '
  foreground = '#D6DEEB'
  background = 'transparent'

[transient_prompt]
  template = ' '
  foreground = '#FEF5ED'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ if .WSL }} on {{ end }}{{ .Icon }} '
    foreground = '#D6DEEB'
    background = '#575656'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      alpine = ''
      android = ''
      arch = ''
      centos = ''
      debian = ''
      elementary = ''
      fedora = ''
      gentoo = ''
      linux = ''
      macos = ''
      manjaro = ''
      mint = ''
      opensuse = ''
      raspbian = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    template = '  {{ .Name }} '
    foreground = '#011627'
    powerline_symbol = ''
    background = '#00C7FC'
    type = 'shell'
    style = 'powerline'

  [[blocks.segments]]
    template = '  admin '
    foreground = '#D6DEEB'
    powerline_symbol = ''
    background = '#EF541C'
    type = 'root'
    style = 'powerline'

  [[blocks.segments]]
    template = '   cmake {{ .Full }} '
    foreground = '#E8EAEE'
    powerline_symbol = ''
    background = '#1E9748'
    type = 'cmake'
    style = 'powerline'

  [[blocks.segments]]
    template = '  {{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }} '
    foreground = '#011627'
    powerline_symbol = ''
    background = '#FFDE57'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'context'

  [[blocks.segments]]
    template = ' ‭ {{ .Full }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#7FD5EA'
    type = 'go'
    style = 'powerline'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#193549'
    powerline_symbol = ''
    background = '#99908A'
    type = 'rust'
    style = 'powerline'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#CAEBE1>  {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#011627'
    powerline_symbol = ''
    background = '#1BD4CD'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#16B1AC{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#16B1AC{{ end }}', '{{ if gt .Ahead 0 }}#B787D7{{ end }}', '{{ if gt .Behind 0 }}#B787D7{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    foreground = '#414141'
    background = '#03DED3'
    type = 'status'
    style = 'diamond'
    foreground_templates = ['{{ if gt .Code 0 }}#D6DEEB{{ end }}']
    background_templates = ['{{ if gt .Code 0 }}#E44141{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ .FormattedMs }} '
    foreground = '#D6DEEB'
    background = '#575656'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 0.0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╭─'
    foreground = '#D6DEEB'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    leading_diamond = '<#B6D6F2>  </>'
    template = ' {{ .Path }}'
    foreground = '#B6D6F2'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      folder_icon = '  '
      folder_separator_icon = '  '
      home_icon = ' '
      max_depth = 3.0
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '<#79DFE1>|</>  {{ .Premium.Remaining.Gauge }} '
    foreground = '#B6D6F2'
    type = 'copilot'
    style = 'diamond'

    [blocks.segments.properties]
      http_timeout = 1000.0

    [blocks.segments.cache]
      duration = '5m'
      strategy = 'session'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─'
    foreground = '#D6DEEB'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = '❯ '
    foreground = '#D6DEEB'
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true
